### PR TITLE
python script to flash blink.ihx

### PR DESCRIPTION
**Pull request by matlab22**
python script to flash blink.ihx, there is also a mcuerase function. but I can not test it.

it is possible to change the hexfile to something else. Therefore you have to modify
if send_file_content(ser, 'blink.ihx'): on line 279 to the new file

feel free to change and further improve it

### CODE REVIEW

**Comment by mightymos** [comment]
Give me some time to update the OnbrightFlasher sketch.
I am changing the function calls over to use those compatible with both SoftWire or Wire libraries.
That way hardware I2C can be used if desired with just a single line change.

At the same time I will try to make serial messages more standard so parsing is simpler.
But it would then require some changes to your script.

I will try to get things stable so there are few changes going forward.

**Comment by mightymos** [comment]
I changed the sketch to support SoftWire and Wire libraries.
I think the serial output should be easier to parse now with checkError().
Sorry to delay merge.

Do you want to change the pull request or I'll merge this one and you could make a new one in the future?

**Comment by matlab22** [comment]
Do whatever suits you best. I am busy this weekend, I can have a look at the changes on Tuesday.

**Comment by matlab22** [comment]
Could you perhaps describe in detail, what the script should send and what it has to expect, then I can easily modify the script?
Especially for the part, where the controller is protected and needs to be cleared.

**Pull request merged**
